name: CI/CD Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Клонуєм репозиторій
        uses: actions/checkout@v4

      - name: Ставим PHP і залежності
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, bcmath, intl, gd, sqlite3

      - name: Вставновлює залежності композера
        run: |
          composer install --prefer-dist --no-interaction --optimize-autoloader

      - name: Деплой на сервер
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: 21098
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

          sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST << 'EOF'
            cd sofa
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:clear
            php artisan cache:clear
            php artisan optimize
            echo "Деплой пройшов успішно!"
          EOF
