name: Deploy Laravel Application

on:
  push:
    branches:
      - main  # або ваша основна гілка для деплою

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout коду з репозиторію
      - name: Check out repository code
        uses: actions/checkout@v4

      # 2. Налаштування PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, bcmath, intl, gd, sqlite3

      # 3. Встановлення залежностей через Composer
      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-interaction --optimize-autoloader

      # 5. Дебаг для виведення значень SSH_USER та SSH_HOST
      - name: Debug SSH variables
        run: |
          echo "SSH_USER: ${{ secrets.SSH_USER }}"
          echo "SSH_HOST: ${{ secrets.SSH_HOST }}"

      # 6. Підключення через SSH та деплой за допомогою пароля
      - name: Deploy to server via SSH
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: 21098  # Вказуємо порт SSH
        run: |
          # Встановлення необхідних інструментів для підключення по SSH
          sudo apt-get update
          sudo apt-get install -y sshpass

          # Підключення до сервера через SSH за допомогою пароля і порту
          sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST << 'EOF'
            # Команди для деплою на сервер
            cd /path/to/your/laravel/project
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:clear
            php artisan cache:clear
            php artisan optimize
          EOF
